version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
    restart: unless-stopped

volumes:
  postgres_data: